version: 2

build:
  os: ubuntu-24.04
  tools:
    python: mambaforge-23.11
  jobs:
    pre_build:
      - pip install -v .

conda:
  environment: docs/environment-docs.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
